---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My First Group:
    - Ubiquity:
        icon: ubiquiti-networks.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: https://10.0.1.1
        description: Dream Machine Pro-SHIELD
    - Proxmox:
        icon: proxmox.png # icons found here https://github.com/walkxcode/dashboard-icons
        href: https://10.0.1.21:8006
        description: PVE-01
    - Proxmox:
        icon: proxmox.png # icons found here https://github.com/walkxcode/dashboard-icons
        href: https://10.0.1.22:8006
        description: PVE-02

- My Second Group:
    - Linkstack:
        href: https://ryan.mccawley.me
        description: Links

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
